
# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [1]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(5,)
1
5
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [2]:
matrix=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]



# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [6]:
arr=np.array([10,20,30,40,50])
print(arr[1])
print(arr[3])
print(arr[-1])

20
40
50



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [7]:
arr=np.array([10,20,30,40,50,60,70])
print(arr[2:6])

[30 40 50 60]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [9]:
arr=np.array([10,20,30,40,50])
print(arr[[1,4,2]])

[20 50 30]



# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [23]:
arr=np.array([10,20,48,90,1,13,15,16,12])
print(arr[np.where(arr>15)])

[20 48 90 16]



# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [24]:
arr=np.array([1,2,3,4,5])
print(arr+5)

[ 6  7  8  9 10]



# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [25]:
arr=np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.min(arr))

150
30.0
10
10



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [26]:
arr=np.array([50,40,30,20,10])
print(np.sort(arr))

[10 20 30 40 50]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [29]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.concatenate([a,b]))

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
print(np.vstack([a,b]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
print(np.hstack([a,b]))

[ 1  2  3  4  5  6  7  8  9 10]
